### ISSUE TITLE
`x-notion-active-user-header` not handed down to page block

### ISSUE THREAD

**Issue by nfilzi** [danmurphy1217/notion-ruby#13]
When attempting to use `page.children`, or `page.get_block('<BLOCK_ID>')`, I get empty results back.

I believe I tracked down the bug to this part:

```ruby
# notion-ruby/lib/notion_api/core.rb:139
def get_all_block_info(_clean_id, body)
      # ! retrieves all info pertaining to a block Id.
      # ! clean_id -> the block ID or URL cleaned : ``str``
      Core.options['cookies'][:token_v2] = @@token_v2
      Core.options['headers']['x-notion-active-user-header'] = @active_user_header # <--- 🚨
      cookies = Core.options['cookies']
      headers = Core.options['headers']
# [...]
```

When `pry-byebugging` it, I get `nil` when checking up `@active_user_header`, and the correct header value when checking up `@@active_user_header`. 
I made the replacement in the source code installed on my system, and it looks like it fixed the issue.

What do you think?

**Comment by danmurphy1217** [comment]
Yep, you're right, that's the issue. Both `token_v2` and `active_user_header` are set to be class variables in `initialize` in **core.rb**:

```ruby
def initialize(token_v2, active_user_header)
      @@token_v2 = token_v2
      @@active_user_header = active_user_header
end
```

I'll push the fix now.

**Comment by danmurphy1217** [comment]
#14 ✔️
