### ISSUE TITLE
Failed to run method get_page

### ISSUE THREAD

**Issue by Shalashtein** [danmurphy1217/notion-ruby#15]
I installed the gem, and put this code into my seed file

```
require 'notion_api'
@client = NotionAPI::Client.new("...")
@page = @client.get_page("05624583c9f442dfa8413368a23ed869")
```
but when I run the file I get the error
`the URL or ID passed to the get_page method must be that of a Page Block.`
even though the token is correct, anf the page ID was copied directly from the view

**Comment by danmurphy1217** [comment]
Looks like you're working with a full-page collection view? Will push a fix for that now

**Comment by danmurphy1217** [comment]
See [here](https://github.com/danmurphy1217/notion-ruby/commit/62154384242788f80ab3afbe8bafce2bde1f8f4d). The latest version of the gem is now available.

You can now retrieve "Full Page" Collection Views. Thanks for bringing this to my attention, and let me know if there's any additional functionality you'd find useful!:thumbsup:

One of the main features in the pipeline right now is the ability to assign new values to a row in a table, so keep an eye out for that in the next few days.

**Comment by Shalashtein** [comment]
Thanks, looking great, appreciate the effort, I just wanted to use the gem to seed my database, I used CSV for now, but this gem makes it easier.
