### ISSUE TITLE
Adding images doesn't work

### ISSUE THREAD

**Issue by npupko** [danmurphy1217/notion-ruby#29]
Adding images doesn't work (By URL and with source file)
```ruby
@page.create(NotionAPI::ImageBlock, file_url)
```
just creates an empty image block

**Comment by danmurphy1217** [comment]
Hi, @npupko! thanks for opening this issue.

Yes, I haven't quite polished off that feature yet (was waiting to see how the gem was received by the ruby community, glad you're using it and hope it's been helpful!). 

With Notion, there are two specific ways files are uploaded: via URL or via a file path. I will work on implementing both of these features, although there will likely be a little refactoring that I do to clean up the code. Given that, it might take me a few days to implement and publish the updated gem:smile:. I will keep you updated

**Comment by danmurphy1217** [comment]
@npupko, 
See #30. Pushed a lot of re-factoring and now you can create an ImageBlock with a URL using:
```ruby
>>> page.create(NotionAPI::ImageBlock, "Title for Block", options: {image: "<URL>"})
```
This design will support some further customization of images down the road (for example, width and height properties), which I figure offers good flexibility should it be necessary to implement. Also, the next push to this PR will support uploading a file path.

Sorry for the long turnaround, I anticipate I'll push these changes out in a new gem version by the end of the week.

**Comment by npupko** [comment]
@danmurphy1217 Everything is cool, thanks a lot for the quick feedback.
