### ISSUE TITLE
Link block

### ISSUE THREAD

**Issue by jonhainstock** [danmurphy1217/notion-ruby#31]
Hey @danmurphy1217, thanks so much for your work on this gem! Do you have plans to add link blocks? If not, I can fork and try to add.

**Comment by jonhainstock** [comment]
Wow, thank you so much!

**Comment by danmurphy1217** [comment]
Hey @jonhainstock, see PR #32. This functionality is now available in [version 1.1.4](https://rubygems.org/gems/notion). I will update the README with an example now, but there is also an example included in the PR.

Let me know if you run into any trouble!

**Comment by jonhainstock** [comment]
Thank you so much, Dan! I'll give it a spin.
